import Head from 'next/head'
import { Carousel } from "react-responsive-carousel";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import PhotosGrid from './photoGrid'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className='carousel_wrapper'>
        <Carousel autoPlay>
          <div className='individual_carousel_wraper'>
            <img
              alt=""
              src="https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?ixlib=rb-4.0"
            />
            <p className="legend">Legend 1</p>
          </div>
          <div className='individual_carousel_wraper'>
            <img
              alt=""
              src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3"
            />
            <p className="legend">Legend 2</p>
          </div>
          <div className='individual_carousel_wraper'>
            <img
              alt=""
              src="https://images.unsplash.com/photo-1579724186435-56a4bd84ab31?ixlib=rb-4.0.3"
            />
            <p className="legend">Legend 3</p>
          </div>
        </Carousel>
      </div> */}

      <div className='banner__wrapper'>
        <div className="banner__img__wrapper">
          <img src="https://images.unsplash.com/photo-1571867424485-369464ed33cc?ixlib=rb-4.0.3" alt="" />
        </div>
        <div className='banner__title'>
          <h3>Our Vibrant Launch Ever</h3>
          <p>The softest, coziest merino wool is back and bigger than ever.</p>
          <div className='banner__buttons'>
            <button>Shop Men</button>
            <button>Shop Women</button>
          </div>
        </div>
      </div>
      <br/>
      <div className="grid__wrapper">
      <h1>Our Best Selling Gems</h1>
        <PhotosGrid/>
      </div>


    </div>
  )
}
